[versions]
java        = "25"
lombok      = "1.18.42"
idea-ext    = "1.3"
annotation  = "26.0.2"
shadow      = "9.2.2"
log4j       = "2.25.2"
infra       = "1.0-SNAPSHOT"

[libraries]
lombok      = { module = "org.projectlombok:lombok",            version.ref = "lombok" }
log4j-api   = { module = "org.apache.logging.log4j:log4j-api",  version.ref = "log4j" }
annotation  = { module = "org.jetbrains:annotations",           version.ref = "annotation" }
infra       = { module = "org.forseason.core:redis",            version.ref = "infra" }

[plugins]
idea-ext    = { id = "org.jetbrains.gradle.plugin.idea-ext",       version.ref = "idea-ext" }
shadow      = { id = "com.gradleup.shadow",                        version.ref = "shadow" }
